use std::path::{Path, PathBuf};

// With an app ACL manifest, Tauri checks app commands against capabilities
// for every caller. Without one, any page on the app's local origin may call
// them. The command list is read from generate_handler! so it cannot drift;
// capabilities/default.json grants the set to the `main` webview only.
fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let main_rs = manifest_dir.join("src").join("main.rs");
    println!("cargo:rerun-if-changed={}", main_rs.display());
    let commands = app_commands(&std::fs::read_to_string(&main_rs).expect("read src/main.rs"));
    let dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("app-acl");
    std::fs::create_dir_all(&dir).expect("create app-acl dir");
    write_if_changed(&dir.join("app.toml"), &permission_file(&commands));
    let pattern: &'static str = Box::leak(
        format!(
            "{}{}*",
            glob_escape(&dir.to_string_lossy()),
            std::path::MAIN_SEPARATOR
        )
        .into_boxed_str(),
    );
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().permissions_path_pattern(pattern));
    if let Err(e) = tauri_build::try_build(attributes) {
        println!("{e:#}");
        std::process::exit(1);
    }
}

/// Command names registered in `tauri::generate_handler![...]`.
fn app_commands(main_rs: &str) -> Vec<String> {
    const OPEN: &str = "generate_handler![";
    let start = main_rs
        .find(OPEN)
        .expect("generate_handler! in src/main.rs")
        + OPEN.len();
    let len = main_rs[start..]
        .find(']')
        .expect("end of generate_handler!");
    let names: Vec<String> = main_rs[start..start + len]
        .lines()
        .map(|l| l.split("//").next().unwrap_or_default())
        .flat_map(|l| l.split(','))
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(|s| s.rsplit("::").next().unwrap_or(s).to_string())
        .collect();
    assert!(
        !names.is_empty()
            && names
                .iter()
                .all(|n| n.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')),
        "could not read the generate_handler! list in src/main.rs: {names:?}"
    );
    names
}

fn permission_file(commands: &[String]) -> String {
    let allow = commands
        .iter()
        .map(|c| format!("\"{c}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "# Generated by build.rs from generate_handler! in src/main.rs.\n\
         [default]\n\
         description = \"Every Parzi app command.\"\n\
         permissions = [\"app-commands\"]\n\
         \n\
         [[permission]]\n\
         identifier = \"app-commands\"\n\
         description = \"Every Parzi app command.\"\n\
         commands.allow = [{allow}]\n"
    )
}

fn glob_escape(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '[' | ']' | '*' | '?' => format!("[{c}]"),
            c => c.to_string(),
        })
        .collect()
}

fn write_if_changed(path: &Path, body: &str) {
    if std::fs::read_to_string(path).is_ok_and(|old| old == body) {
        return;
    }
    std::fs::write(path, body).expect("write app permissions");
}
