[package]
name = "parzi-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
parzi-core = { path = "../parzi-core" }
parzi-providers = { path = "../parzi-providers" }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync", "time", "process", "fs", "io-util", "io-std", "net"] }
tokio-util = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }
async-trait = "0.1"
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"
bytes = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls-manual-roots"] }
pdf-extract = "0.12.1"
base64 = "0.23.1"

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json"] }
